// Generated by `npm run images` from raw-assets/. Do not edit by hand.
/** Processed image base names → the widths written to public/images/. */
export const PROCESSED_IMAGES: Readonly<Record<string, readonly number[]>> = {
  "case-001-sentinel-1": [
    393
  ],
  "case-001-sentinel-2": [
    386
  ],
  "case-001-sentinel-3": [
    480,
    960,
    1440
  ],
  "case-002-learntes-1": [
    480,
    960,
    1440
  ],
  "case-002-learntes-2": [
    480,
    529
  ],
  "case-002-learntes-3": [
    480,
    960,
    1440
  ],
  "case-003-medscript-1": [
    480,
    960,
    1440
  ],
  "case-003-medscript-2": [
    480,
    960,
    1440
  ],
  "case-003-medscript-3": [
    480,
    960,
    1376
  ],
  "case-004-shelfsense-1": [
    291
  ],
  "case-004-shelfsense-2": [
    300
  ],
  "case-004-shelfsense-3": [
    480,
    960,
    1440
  ],
  "history-edusphere": [
    480,
    960,
    1440
  ],
  "portrait": [
    480,
    922
  ]
};
export const HAS_RESUME = true;
export const OWNER_LINKS: Readonly<Record<string, string>> = {
  "github": "https://github.com/ARCHIT3024",
  "linkedin": "https://www.linkedin.com/in/archit-khandelwal3024",
  "shelfsense-github": "https://github.com/ARCHIT3024/ShelfSense",
  "medscript-github": "https://github.com/ARCHIT3024/Medscript",
  "medscript-huggingface": "https://huggingface.co/Witcherr00/medscript-mistral-7b-qlora",
  "learntes-github": "https://github.com/ARCHIT3024/Learntes",
  "learntes-date": "Jan – Feb 2026",
  "learntes-aws": "S3, CloudFront, Lambda, API Gateway, RDS and Cognito",
  "sentinel-github": "https://github.com/ARCHIT3024/Sentinel-Damage-Assessment"
};
